[package]
authors = ["Dan Lionis <lionis.dan@gmail.com>"]
edition = "2018"
name = "discord"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.8"
chrono = { version = "0.4", features = ["serde"] }
dashmap = { version = "3.11", optional = true }
hyper = { version = "0.14", features = ["http1", "client", "tcp"] }
hyper-tls = "0.5"
log = "0.4" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_repr = "0.1"
url = "2.2"
lru = "0.7.0"

[dev-dependencies]
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
serde_test = "1.0"
tokio-tungstenite = { version = "0.13", features = ["tls"] }
futures = "0.3"


[features]

full = [ "cache" ]

cache = [ "dashmap" ]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "ping"
