[package]
authors = ["Dan Lionis <lionis.dan@gmail.com>"]
edition = "2018"
name = "discord"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
url = "2.2"
http = "0.2"
serde_json = "1.0"
serde_repr = "0.1"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
lru = { version = "0.7.0", optional = true }
dashmap = { version = "3.11", optional = true }
reqwest = { version = "0.11", features = ["json"], optional = true }

[dev-dependencies]
env_logger = "0.9"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
serde_test = "1.0"
tokio-tungstenite = { version = "0.13", features = ["tls"] }
futures = "0.3"


[features]
full = ["cache", "reqwest"]
cache = ["dashmap", "lru"]
rest = ["reqwest"]

[package.metadata.docs.rs]
all-features = true

[[example]]
name = "ping"
