[package]
authors = ["Dan Lionis <lionis.dan@gmail.com>"]
edition = "2018"
name = "discord"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6"
async-tungstenite = {version = "0.8", features = ["tokio-runtime", "tokio-native-tls"]}
chrono = {version = "0.4", features = ["serde"]}
# env_logger = "0.7"
futures = "0.3"
hyper = "0.13.6"
hyper-tls = "0.4.1"
log = "0.4"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
simple_logger = "1.11"
tokio = {version = "0.2", features = ["full"]}
